package com.uol.organism.cell.multi_cell.eukaryote.plant;

import com.uol.organism.cell.Cell;

/**
 * Phloem is a specialised tissue for food transport in higher plants, mainly transporting sucrose along pressure
 * gradients generated by osmosis, a process called translocation.
 *
 * @author RandomCatGit
 */
public class Phloem extends Cell {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = 0L;

	/**
	 * Default constructor of RWO StemCell
	 */
	public Phloem() {
		super(null);
	}

}
